
        os: osx
        name: IOS
        osx_image: xcode11.4
        install:
            - git clone https://github.com/flutter/flutter.git -b stable
            - export PATH=$PWD/flutter/bin:$PWD/flutter/bin/cache/dart-sdk/bin:$PATH
            - gem install bundler
            - cd ios && bundle install && cd ..
        script:
            -  travis_wait 60 flutter build ios  --release --no-codesign
            -  cd ios
            -  bundle exec fastlane deployStaging
