name: cuthair
description: Aplicacion para la peluqueria


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  font_awesome_flutter: ^8.5.0
  firebase_core: ^0.4.3+2
  firebase_auth: ^0.15.3+1
  flutter_auth_buttons: ^0.6.0
  toast: ^0.1.5
  flutter_facebook_login: ^3.0.0
  sms: ^0.2.4
  cupertino_icons: ^0.1.2
  flutter_calendar_carousel: ^1.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
    - assets/images/
