name: cuthair
description: Application for the control and management of appointments.

version: 1.0.0+6

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  font_awesome_flutter: ^8.5.0
  dbcrypt: 1.0.0
  firebase_core: 0.4.4
  firebase_auth: 0.15.4
  http: ^0.12.0+4
  flutter_auth_buttons: ^0.6.0
  flutter_facebook_login: ^3.0.0
  flutter_calendar_carousel: ^1.4.10
  firebase_storage: 3.1.3
  cloud_firestore: 0.13.7
  sqflite: ^1.3.0
  carousel_slider: ^1.4.1
  flutter_spinkit: ^3.1.0
  flutter_sms: ^1.1.0
  path_provider: ^1.6.5
  url_launcher: ^5.4.2
  flutter_svg: 0.17.4
  simple_connectivity: 0.1.1
  firebase_messaging: ^5.1.4
  sms: 0.2.4
  qr_flutter: ^3.1.0
  crypto: ^2.1.3
  flutter_dotenv: ^2.1.0
  filterlist:
    git:
      url: git://github.com/Domirop/FiltersPackage.git
  components:
    git:
      url: git://github.com/Domirop/Components.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"

flutter_icons:
  ios: false
  android: true
  image_path: "assets/images/logo/playstore.png"
  adaptive_icon_background: "assets/images/logo/R-Bg.png"
  adaptive_icon_foreground: "assets/images/logo/R-logo.png"




flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - env_files/debug.env
    - env_files/release.env
