# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
setup_travis
default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :deployStaging do
    sync_code_signing(type: "appstore", app_identifier:"capihair.cuthair",readonly:is_ci)
    build_app(scheme: "Staging", export_method:"app-store")
    upload_to_testflight(skip_waiting_for_build_processing:true)
    end

    desc "Deploy a new version to the App Store"
    lane :deployProd do
      sync_code_signing(type: "appstore",app_identifier:"capihair.cuthair", readonly:is_ci)
      build_app(scheme:"Prod", export_method:'app-store')
      buildNotes = File.read("../../build_notes.txt")
      upload_to_app_store(release_notes:{"default": buildNotes})
  end
end