# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  def get_version_code
    properties = File.read("../local.properties")
    versionCodeRegex = /(?<=flutter.versionCode=).+/
    versionCode = versionCodeRegex.match(properties)[0]
    versionCode  
  end

  desc 'Deploy a new RC version to Google Play'
  lane :deployStaging do
    upload_to_play_store(
      track: 'internal',
      package_name: 'capihair.cuthair',
      aab: '../build/app/outputs/bundle/release/app-release.aab'
    )
  end
end
